// Protect from multiple includes
#ifndef VAMK_CONFIG_H
#define VAMK_CONFIG_H

//Imports

//Serial Config
#define SERIAL_BAUD_RATE 9600

//I2C Config
#define I2C_CLOCK_SPEED 100*1000 //100Khz

#define PRIMARY_KEYBOARD_ADDRESS 0x2A
#define SECONDARY_KEYBOARD_ADDRESS 0x45

#define OLED_PRIMARY_SCREEN_ADDRESS 0x3C
#define OLED_SECONDARY_SCREEN_ADDRESS 0x3D

#define OLED_SCREEN_WIDTH 128
#define OLED_SCREEN_HEIGHT 64

//Keyboard Config
#define SWITCH_TESTING_MODE 0
#define ENABLE_SERIAL_LOGGING 0
#define ENABLE_KEYBOARD_COMMANDS 0

#define IS_PRIMARY_KEYBOARD_SIDE 1

#define COLUMN_COUNT 7
#define ROW_COUNT 3

#endif
